name: pull_to_reveal_flutter
description: >-
  A Flutter package that enables WeChat-style hard pull-to-reveal interactions,
  exposing a hidden background layer with smooth resistance physics and
  configurable animation modes.
version: 0.1.2

repository: https://github.com/AmriliDigitalServicesLTD/pull_to_reveal.git


environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: